# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  # defined at https://github.com/snowdrop/circleci-orbs
  # needs to have been published before being used here
  openshift: snowdrop/openshift@0.3.0

jobs:
  JDK8:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v8-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v8-dependencies-

      - run: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v8-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test -Pwith-examples
  JDK11:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v11-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v11-dependencies-

      - run: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v11-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test -Pwith-examples

  OPENSHIFT_3_11:
    machine: true
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v8-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v8-dependencies-

      - run: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v8-dependencies-{{ checksum "pom.xml" }}
      - openshift/launch_openshift_311
      - run:
          name: Run build on openshift
          command: |
            oc login -u admin -p admin
            oc new-project itests
            mvn -B install -Pbuild -Pwith-examples

workflows:
  version: 2
  build_and_test:
    jobs:
      - JDK8
      - JDK11
      - OPENSHIFT_3_11
