name: Publish the website
on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        run: |
          sudo apt-get install moreutils
          .github/set-version.sh $GITHUB_REF_NAME
      - name: Commit files
        run: |
          git config --global user.name "Dekorate"
          git config --global user.email "cmoullia-staff@redhat.com"
          git add docs/_data/project.yml
          git status
          echo $GITHUB_REF_NAME
          git commit -m "chore: update project version for Dekorate docs."
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: gh-pages
